Katello/katello-installer

hooks/pre/15-check_java.rb

Our error messages were not hard-wrapped.
Also added info about how to set default Java in case both OpenJDK and GCJ were
installed (and GCJ as later package):
alternatives --config java

Improved java check error messages

---

config/capsule-certs-generate.yaml
config/capsule-installer.yaml
config/katello-installer.yaml
config/sam-installer.yaml
katello-installer.spec

See: https://github.com/theforeman/kafo/commit/1185cf813a392c63029a4ddcd4beca28b9e88034.  
capsule-installer hooks are in a common directory `/usr/share/katello-installer` and aren't being loaded.  It was working before because Kafo also looks in the installer directory itself, but now these are separated.

fixes #9075 - hooks_dir should be hook_dirs

---

Puppetfile.lock
modules/candlepin/Gemfile
modules/gutterball/Gemfile
modules/katello/.fixtures.yml
modules/katello/Gemfile
modules/katello/manifests/config.pp
modules/katello/manifests/init.pp
modules/katello/manifests/params.pp
modules/katello/manifests/service.pp
modules/katello/metadata.json
modules/katello/spec/classes/katello_config_spec.rb
modules/katello/spec/classes/katello_spec.rb
modules/katello/templates/katello.yml.erb

Includes:
- Fixing devel install for gutterball
- Removal of unused config in katello

Fixes #8585: Remove unused configuration from Katello module.

---

Puppetfile.lock
katello-installer.spec
modules/certs/manifests/init.pp
modules/certs/metadata.json
modules/postgresql/.sync.yml
modules/postgresql/.travis.yml
modules/postgresql/Gemfile
modules/postgresql/Rakefile
modules/postgresql/manifests/server/extension.pp
modules/postgresql/manifests/server/initdb.pp
modules/postgresql/manifests/validate_db_connection.pp
modules/postgresql/spec/unit/defines/server/extension_spec.rb
modules/postgresql/spec/unit/defines/server/pg_hba_rule_spec.rb
modules/postgresql/spec/unit/defines/server/pg_ident_rule_spec.rb

openssl is needed for katello-certs-check

Fixes #9888 - require openssl for katello-installer-base

---

hooks/post/10-post_install.rb

On non-rhel systems, users would need to ensure subscription-manager
got installed and then run the bootstrap RPM command. This will
change it such that the bootstrap RPM and it's dependencies are
attempted to be installed more cleanly for users.

Fixes #9809: Use 'yum localinstall' to install sub-man as well.

---

config/answers.katello-installer.yaml

I previously tried to use an empty value to mean empty string but that isn't the same so explicitly setting this value to false.

Refs #10210: Explicitly set CRL to false since empty value is not the same.

---

hooks/boot/01-helpers.rb
hooks/pre/30-upgrade.rb

We only need mongo started; having candlepin running generates some errors in the logs (temporary).  Also, we should just abort if one of the upgrade steps fails instead of silently continuing.

fixes #10221 - handle services and failures better during upgrades

---

hooks/pre/30-upgrade.rb

When user enables new features that weren't previously enbaled, the installer needs access to the repos hosted on the Katello itself.  Having httpd running during the upgrade allows this to happen.

fixes #9680 - ensure httpd is started for access to repos

---

hooks/post/30-upgrade.rb

Pulp database is migrated before pulp-plugins-docker is installed during an uprade, which results in errors like this:
```
Importer docker_importer: no type definition found for docker_image
Jun 05 08:59:09 capsule.stbenjam.satellite.lab.eng.rdu2.redhat.com pulp15120: pulp.server.webservices.application:CRITICAL: *****************************************************
```
The pulp database should be migrated in post, as well, in case we installed any additional pulp plugins.

fixes #10716 - migrate pulp in post as well

---

modules/pulp/manifests/child/config.pp
modules/pulp/manifests/child/fragment.pp
modules/pulp/templates/etc/httpd/conf.d/_pulp_node_ssl_include.erb

The Apache 1.1.X module does not contain the ability to concat fragments
directly onto the apache vhost which is what this version of the installer
contains.

Fixes #11041: Setup GPG fragment properly for Apache 1.1.X module.

---

hooks/post/30-upgrade.rb

This restructures the post hook to look like and have the same resiliency of the pre hook.

fixes #11086 - error out when upgrade post tasks fail

---

migrate/answers.katello-installer.yaml/02-templates_off.yaml

I'm like 0 for 2 today.  https://github.com/Katello/katello-installer/pull/243 was not a complete fix. Templates would still get enabled on an upgrade, we need a migration to add it to existing answers.

refs #10675 - templates off by default for upgrade, too

---

Rakefile

This also moves the compression format over to gzip to follow the
style that github uses since that is where we grab/store our archives.

Fixes #11334: Change to gzip to mimic Github's compression

---

Rakefile

Successive runs of the rake task that generates package tarballs
did not remove or overwrite the previous builds. In a local or CI
environment, the tarball built could unknowingly result in no
updates and a stale package.

Fixes #11666: Cleanup _build and pkg directories between runs

---

bin/katello-certs-check

updated script to take into account new installs, as the --update-certs flag is not needed for a 1st time run

Fixes #11856 - Updating katello-certs-check #265

---

config/answers.katello-installer.yaml
config/katello-installer.yaml
migrate/answers.katello-installer.yaml/04-remote_execution.yaml
migrate/katello-installer.yaml/02-remote_execution.yaml

Still a WIP, need to figure out how to handle the foreman proxy plugins, as foreman proxy isn't at the top level.

fixes #12000 - support remote execution in installer

---

config/answers.capsule-installer.yaml
config/answers.katello-devel-installer.yaml
config/answers.katello-installer.yaml
config/capsule-installer.yaml
config/katello-devel-installer.yaml
config/katello-installer.yaml
hooks/post/10-post_install.rb

This commit contains some initial changes to support the puppet-capsule
changes that decouple puppet-foreman_proxy from the puppet-capsule.
(Ref: https://github.com/Katello/puppet-capsule/pull/64)
The following is an example to install katello using this configuration:
```
katello-installer
```
The following is an example to install capsule using this configuration:
```
capsule-installer --register-in-foreman "true"\
--registered-proxy-url "https://capsule.example.com:9090"\
--oauth-consumer-key "pvUutwvPU3Rni5RWqisL6Tx4fAF5yDSa"\
--oauth-consumer-secret "JTGnd3fx6GB4uki5LtNPFU6cCSq9NrFk"\
--foreman-base-url "https://katello.example.com"\
--trusted-hosts "katello.example.com"\
--trusted-hosts "capsule.example.com"\
--parent-fqdn "katello.example.com"\
--pulp-oauth-secret …
```

fixes #10533 - update answers and config to decouple foreman_proxy from capsule

---

README.md

Several changes were made to enable installing katello and the capsule
as 'scenarios' using the foreman-installer.
This commit contains changes to the katello-installer to reflect the
updated behavior, which primarily affect the commands to install
the katello and capsule (i.e. foreman-installer --scenario [katello|capsule])
and changes to the input parameters as we also separated the
puppet-capsule from foreman-proxy.

fixes #13892 - update the README to reflect the scenario-based installer

---

hooks/post/10-post_install.rb

The 'capsule' scenario is included as part of the 'foreman-installer-katello' rpm.

fixes #13956: fix the installer rpm name needed to install a capsule

---

config/katello-devel.migrations/20160301144353-order.rb

Crane configuration ended up with the wrong certs and key because
certs::apache in the capsule module was not resolving when the
module was evaluated.

Fixes #13924: Ensure proper ordering for devel dependencies

---

hooks/pre/30-upgrade.rb

This removes node importers from repositories on a capsule and node distributors from repositories on the main katello server as they are no longer needed because of the [nodes removal work that has been done.](https://github.com/Katello/katello/pull/5778)

Fixes #13198 - remove node importers and distributors from repos

---

hooks/post/30-upgrade.rb

The follow-up PR for Katello itself is:
https://github.com/Katello/katello/pull/5906

Fixes #14241 - removing old upgrade steps we no longer support

---

bin/capsule-installer
bin/katello-installer

This commit contains 2 small changes to help aide users in moving to the
new installer.  Rather than remove the old commands, we will include them;
however, simply echo the new command and exit with an error code.

fixes #14416 - Add katello-installer/capsule-installer to inform user of new installer

---

hooks/post/10-post_install.rb

Currently, the admin password continues to be shown on subsequent runs,
even if the user has already changed it. This creates a .installed file
in the Kafo config file directory after the first successful install, to
ensure we only print out the credentials on the very first run.

fixes #14254 - only show admin password on first successful install

---

config/answers.sam-installer.yaml
config/katello-answers.yaml
config/katello.migrations/160516145300-foreman-client-certs.rb

puppet-foreman now exposes the foreman client certificates through
parameters. Since Katello wants to change these from puppet to custom
handling, these must be set. puppet-certs currently attempts to do so
through foreman-rake config. Since puppet-foreman has started to set
these in settings.yaml, they can't be overridden anymore. By setting
these in the answers file, we avoid that conflict.

fixes #15063 - set answers for foreman client certs

---

hooks/pre/30-upgrade.rb

This is an alternative approach to #338 where I am centralizing all the "unique" logic required for these upgrades into the pre-upgrade script and attempting to provide as much idempotent behavior as possible. Another approach would be to add "upgrade.d" functionality similar to migrations and mark upgrades that have run and perform these there. 
Note: This is only from a 2.3 to 3.0 upgrade which we say we support currently. There is one outstanding issue with this that I did not include a fix for yet. The Foreman PR (https://github.com/theforeman/foreman/pull/3519) is not currently in 1.11 and the migrations fail because of it. As I see it our options then are:
1) Push to get https://github.com/theforeman/foreman/pull/3519 into 1.11.3 and wait for GA until then
2) Add upgrade …

Fixes #15117 - Upgrade steps required for 2.3 to 3.0

---

hooks/pre/30-upgrade.rb

RHEL 6 uses http 2.2 which does not have the conf.d/ directory structure. adding 
```Include "/etc/httpd/conf.modules.d/*.conf"``` causes errors in RHEL 6.
This adds a check for http 2.4 in the http.conf, which will only include the conf.d/ directory in RHEL 7 systems

Fixes #15072 - RHEL 6 http conf doesn't have conf.d dir structure

---

config/katello.migrations/160526130623-server-ssl-crl.rb

In some upgrade scenarios, this field is not being set during the
legacy migration step.

Fixes #15203: Set server_ssl_crl to false through migration

---

bin/create-migration

Basic migration generator script that ensure the proper timestamp
formatted file is created in the place you want it.

Fixes #15205: Add migration creator script

---

hooks/post/30-upgrade.rb

One small thing I found in testing  upgrade w/ gutterball removal.  The gutterball dir isn't removed.  It's empty, but Tomcat still tries to "deploy" it:
```
May 27 16:39:44 centos7-2-4.example.com server[10839]: INFO: Deploying web application directory /var/lib/tomcat/webapps/gutterball
```

fixes #14858 - remove gutterball directory

---

checks/proxy.rb

Created proxy check for katello-installer to verify if a proxy env is set.

Fixes #14956 - Check for proxy before katello-installer runs

---

hooks/post/30-upgrade.rb

The gutterball removal requests the removal of a handful of packages.
If any are missing with `rpm -e`, the entire command will fail.
However, if you use `yum erase`, the missing packages will not cause an
issue and the remaining packages will be removed. Additionally, `yum
erase` will return a zero exit code in this case.

Fixes #15277 - use `yum erase` instead of `rpm -e`.

---

hooks/post/10-post_install.rb

capsule-certs-generate does not honour "--parent-fqdn" parameter 
The parent fqdn is set as the actual hostname of the satellite server where we execute capsule-certs-generate command.

Fixes #14978 - capsule-certs-generate does not honour "--parent-fqdn" parameter

---

hooks/post/30-upgrade.rb

This commit includes a post upgrade task to perform
updates to the puppet repositories (e.g associate
puppet distributor & publish).

fixes #15297: post upgrade to update puppet repositories

---

hooks/pre/20-certs_update.rb

katello-certs-check is either in the katello-installer directory
(git repo) or in foreman-installer-katello (rpm install).  This supports
both cases.
For 3.1, would it just make sense to combine these into 2 packages? I wasn't sure if there's a technical reason for why we keep foreman-installer-katello and katello-installer-base as 2 separate packages.

fixes #15158 - support multiple paths for katello-certs-check

---

hooks/post/10-post_install.rb

for 'capsule_certs' and 'parent_fqdn'
BATs are failing with `/usr/share/katello-installer-base/hooks/post/10-post_install.rb:22:in `block (4 levels) in load': undefined method `value' for nil:NilClass (NoMethodError)`
This was introduced in #332.

Fixes #15325 - Handle nil params

---

config/capsule.migrations/160601202256-additional-foreman-proxy.rb
hooks/pre_migrations/01-migrate_legacy_foreman_installer_config.rb
hooks/pre_migrations/10-migrate_legacy_capsule_config.rb
hooks/pre_migrations/11-migrate_legacy_katello_config.rb

This commit will ensure that during a capsule upgrade
that the foreman url and trusted hosts are populated
correctly from the legacy capsule configuration.
In addition, a change is being introduced to keep the
default log_dir and log_name from the new configurations
versus from the old (e.g. /v/l/capsule-installer).  This
was the intended behavior and is what is used by some
downstreams.

fixes #15315: update capsule foreman url & trusted hosts

---

config/capsule.migrations/160608111430-additional-foreman-proxy.rb
config/katello-devel.migrations/160601202256-additional-foreman-proxy.rb
config/katello-devel.migrations/160608111430-additional-foreman-proxy.rb
config/katello.migrations/160601202256-additional-foreman-proxy.rb
config/katello.migrations/160608111430-additional-foreman-proxy.rb

With the Katello on Foreman feature, there was an effort to separate
the foreman_proxy aspects from the puppet-capsule.  The changes
for this were primarily done as part of:
https://github.com/Katello/puppet-capsule/pull/64
At that time, there were no migration capabilities to move the
answers from the 'capsule' to 'foreman_proxy' within the various
answer files (e.g. answers.katello-installer.yaml &
answers.capsule-installer.yaml).
This commit will add in migrations for each env to support moving
the parameters over.  This includes:
- katello
- katello-devel
- capsule
It should be noted that for katello and katello-devel include
an additional migration.  It is one that was added in a previous
commit for capsule, but it should apply to all environments.

fixes #15350: add migrations for capsule -> foreman_proxy separation

---

config/katello.migrations/160120212701-foreman-proxy.rb
config/katello.migrations/160601202256-additional-foreman-proxy.rb
config/katello.migrations/160608111430-additional-foreman-proxy.rb

Without this check, answers not found already (such as a new
installation) are set to nil instead of the default values provided
by the puppet module.

Fixes #15390: Ignore empty answers during Capsule to Proxy migration

---

hooks/pre_commit/05-puppet_certs_exist.rb

As long as installer hooks are not shared yet among Katello and Foreman scenarios I'm proposing the same hook as in https://github.com/theforeman/foreman-installer/pull/149 also to Katello.
Issue: Puppet is not able to generate proper CA certificates when the client certificate was already generated.
Solution: The installer stops and informs user about the conflicting situation possible causes and fixes
-  the checks are only performed when server CA is true
-  existence of puppet client cert is tested on existence of host priv key
-   the checks can be skipped with --skip-checks-i-know-better switch

Fixes #15241 - fail nicely if puppet certs were already generated

---

hooks/boot/01-helpers.rb

This is especially useful for Pulp migrations as they contain useful
information regarding what stage they are at and if they will be long
running.

Fixes #15660: Print command output during upgrade steps in debug color

---

bin/katello-certs-check

Switching to absolute paths to avoid issues with validate_absolute_path
during upgrades.
Fixes #15775
New format
--------------
```
...
Validation succeeded.
To install the Satellite main server with the custom certificates, run:
satellite-installer --scenario satellite\
--certs-server-cert "/root/sat_cert/test.crt"\
--certs-server-cert-req "/root/sat_cert/test.crt.req"\
--certs-server-key "/root/sat_cert/test.key"\
--certs-server-ca-cert "/root/sat_cert/cacert.crt"
...
```

Fixes #15775 - Use absolute paths instead of relative.

---

checks/hostname.rb
hooks/post/10-post_install.rb

Facter is bundled in the AIO bundle and not accessible to system ruby.  We can just call `hostname -f` anyway.

fixes #15911 - don't use facter anymore in the installer

---

config/katello.migrations/160802130342-certificate-chain-file.rb

the SSLCertificateChainFile is sent to the browser to verify the identity of
the server. The misconfiguration caused, that the user would need to have all
the certificates in the chain installed in the system. After this change, the
ROOT CA is enough to have on the system to verify the server cert.

Fixes #13687 - use the server cert for the certifiate_chain_file

---

hooks/pre/29-remove_sslconf.rb

added a hook to remove "/etc/httpd/conf.d/ssl.conf" which was causing issues with --upgrade being run if the mod_ssl package was upgraded replacing the ssl.conf config file.

Fixes #15380 - remove ssl.conf before installer run

---

hooks/boot/12-clear_puppet_environments.rb
hooks/pre/12-clear_puppet_environments_feature.rb

Previously, the clear puppet environments flag would only clear the
puppet 3 dir. This patch iterates over both the puppet 3 and puppet 4
dirs, cleaning both if the flag is set.

Fixes #16011 - handle both puppet 3 and 4 dirs when cleaning

---

hooks/boot/17-disable_system_checks.rb
hooks/pre/17-memory_check.rb

Added memory check to installer to make sure system has decent ram before running the installer.

Fixes #15696 - Added memory check to installer

---

.rubocop.yml

People using Ruby 2.3.0 are getting a different set of rubocop warnings/errors when they run rubocop locally. This change will prevent that. Using Ruby version 2.0 based on https://git.io/viZBa.

Refs #16354 - Hardcoding ruby version

---

hooks/boot/31-upgrade-puppet.rb
hooks/post/31-upgrade-puppet.rb
hooks/pre/30-upgrade.rb
hooks/pre/31-upgrade-puppet.rb

This enables a `--upgrade-puppet` flag that will upgrade a Katello
installation from Puppet 3 to Puppet 4.
Most of this is based on
http://projects.theforeman.org/projects/foreman/wiki/Upgrading_from_Puppet_3_to_4
and https://github.com/beav/forklift/pull/1.
todo (feel free to add/subtract from this):

Fixes #16053: hooks for puppet 4 upgrade

---

bin/capsule-certs-generate

The script did not have `/usr/share/katello-installer-base/modules` in its
module path, leading to dev setup errors.

Fixes #16541 - add path to `capsule-certs-generate`

---

hooks/pre/18-vm_overcommit.rb

added a check to make sure vm.overcommit is not enabled, which caused some issues downstream

Fixes #16300 - add overcommit memory check

---

checks/hostname.rb

BZ reporter was unhappy with the format of the /etc/hosts suggestion, so this makes it a little more clearer I guess about what's expected.
Also, the way to set the hostname of el6 and el7 is different, and who knows could change again in el8. Users should read the docs on how to do it.

fixes #16929 - make hostname check message clearer

---

hooks/pre/30-upgrade.rb

Rubocop is unhappy 
```
hooks/pre/30-upgrade.rb:138:3: C: Favor a normal if-statement over a modifier clause in a multiline statement.
fail_and_exit 'Concurrent use of --upgrade and --upgrade-puppet is not supported. '\ ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

fixes #17138 - fix rubocop failure

---

.rubocop.yml
.rubocop_todo.yml
config/capsule.migrations/160314145015-qpid-localhost.rb
config/katello-devel.migrations/160314145015-qpid-localhost.rb
config/katello.migrations/160314145015-qpid-localhost.rb
hooks/pre/30-upgrade.rb

Removes the FQDN's for the AMQP hosts so that the new defaults are used (localhost).

fixes #11737 - dispatch router connect to qpid on localhost

---

hooks/post/30-upgrade.rb

Still seeing web app dir after upgrades:
For upgrades from 6.1, that directory remains undeleted, so tomcat still deploys gutterball app despite no gutterball RPM present, no gutterball DB. And that still subscribes to the $(fqdn):event qpid queue and still causes https://access.redhat.com/solutions/2608341 - confirmed in field already.
Switching to an rm -rfv to make sure we remove the dir 100%

Fixes #16864 - remove gutterball webapp directory

---

hooks/pre/31-upgrade-puppet.rb

"nil" will reset the parameter to the puppet default, param.default
contains the current value as it's the "default" from the
answers file if there's one specified (it's poorly named)
After upgrade, puppetca settings are now correct:
``` yaml
---
:enabled: https
:ssldir: /etc/puppetlabs/puppet/ssl
:puppetdir: /etc/puppetlabs/puppet
```

fixes #17074 - set param value to nil for puppet upgrade

---

Rakefile
config/capsule.yaml

There were some fixes in master for capsule parser cache, this commit
is a smaller version to just pull what's needed to build the capsule
parser cache for puppet 4.

Fixes #17124 - install capsule parser cache

---

config/katello-answers.yaml

When syncing the migrations with the answers, I accidentally
removed `group: foreman` from the certs top-level module.  Since
there's no migration that sets the value (it was there since the
beginning) no migration added it back.

fixes #17278 - add group: foreman to certs

---

hooks/post/30-upgrade.rb
hooks/pre/30-upgrade.rb

Finding on some upgrades the event queue is still present, removing from pre and moving to post.

Fixes #16863 - Remove qpid event queue

---

hooks/post/30-upgrade.rb

Fixes this issue that is related to qpid, its not every upgrade or time either. This happens after an upgrade with a manual qpid-stat from the cli too. The queue gets removed just it gives a nasty traceback to the user during the upgrade process. I talked with @mccun934 and he is fine with just suppressing the error. Also added '' around my grep.
Traceback that appears during upgrade is at the bottom of the paste below:
https://paste.fedoraproject.org/483909/40169014/

Fixes #17331 - supress el6 qpid-stat traceback

---

hooks/post/10-post_install.rb

added location on capsule fqdn where to scp the tar file to, since downstream customers are putting it in different spots and causing issues when the installer runs.

Fixes #17214 - add more info about capsule tar

---

config/capsule.yaml

/usr/share/foreman/modules isn't even a path that ever existed.  It only ever worked because it was all on one line before like this:
`:module_dirs: ['foo', 'bar']`
And the sed didn't care what the contents was, but since I added the migration tools in https://github.com/Katello/katello-installer/commit/0174992d0cf90fe577d0c8cf2d005eefe7bd2391, the YAML is outputted differently so it no longer matches the sed.
This PR makes capsule.yaml use the same config as the rest of the scenarios.

fixes #17604 - correct capsule scenario module dir paths

---

hooks/pre/17-memory_check.rb

I just bought Intel NUC with 8GB module for testing Katello and apparently when
I install CentOS 7 and keep KDump feature enabled (which is the default), some
memory is reserved for this, therefore my system reports this:
```
[root@nuc ~]# free
total        used        free      shared  buff/cache   available
Mem:        7928504      427748     4026228        9076     3474528     7150332
Swap:       7812092           0     7812092
[root@nuc ~]# grep MemTotal /proc/meminfo | awk '{print $2}'
7928504
```
This patch changes the check to accept 7.9 GB as 8 GB threshold. If this is a
problem for Katello, I will rewrite the patch and change the error message to
"Minimum 8.1 GB is required" which is really what the check does. But it's
really weird requirement, I am testing with real hardware.

Fixes #17605: Memory check works for real 8 GB

---

hooks/post/11-create_sslconf.rb
hooks/post/29-create_package_httpd_conf.rb
hooks/pre/29-remove_package_httpd_conf.rb
hooks/pre/29-remove_sslconf.rb
hooks/pre/30-upgrade.rb

Like mod_ssl did, pulp package now places a pulp.conf that has a duplicate directive.

fixes #17415 - remove unmanaged httpd conf files

---

hooks/post/29-create_package_httpd_conf.rb
hooks/pre/29-remove_package_httpd_conf.rb

When puppetlabs-apache is released with the fix for this, we no
longer need to worry about the RPM overwriting the ssl.conf
file.
https://github.com/puppetlabs/puppetlabs-apache/pull/1543 was accepted.
This PR mostly as a reminder to myself, it'll probably bit a little while before the change appears in a released version.

fixes #17507 - remove workaround for ssl.conf

---

hooks/post/10-post_install.rb

FOREMAN-PROXY isn't a valid identifier in bash because of the dash, 
so if an user copies and pastes that command, it will never work as that
variable cannot be set. It should be something like FOREMANPROXY
or FOREMAN_PROXY so users can set that variable.

Fixes #17975 - Suggest a valid variable name for proxy-certs-generate

---

hooks/post/29-create_package_httpd_conf.rb
hooks/pre/29-remove_package_httpd_conf.rb

This workaround is not needed anymore, katello now uses the pulp.conf
instead of 05-pulps-https.conf. therefore it doesn't need to delete or
create pulp.conf in hook because it overwrites pulp.conf within the
installer

fixes #18132 - hooks in --noop delete pulp.conf

---

hooks/pre/30-upgrade.rb

Before this patch, we were ignoring the results of db:migrate rake task in
pre-upgrade hook. While sometimes it helped us with issues, when the second run
of db:migrate inside the installer would finish successfully (just because of
some combination plugins or jumping though multiple versions). We should
however rather be aware of the issues and fixing them, rather than ignoring it,
with potential consequences later.

Fixes #17191 - don't continue with upgrade on db migrate error

---

hooks/boot/01-helpers.rb

This patch allows the installer to print output of the upgrade step being run immediately when it is available instead of collecting the output and printing it after the command finishes.
It should improve user experience during the long running upgrades by providing visual indication that upgrade is in the progress. Improvements in the output of the long running tasks will follow.

Fixes #17192 - Show output during upgrade step run

---

hooks/pre/29-remove_package_httpd_conf.rb

!katello is not the same as a proxy with content, as the hooks
also get run by foreman-proxy-certs-generate.  This causes the pulp.conf to get deleted on a Katello when generating proxy certs.

fixes #18402 - only delete pulp.conf explicitly on a proxy

---

hooks/post/30-upgrade.rb

An example of a test run on new the new code:
https://paste.fedoraproject.org/541210/79914414/
To test I just added :always_run => true to the steps for es/gutterball so the installer will run that task.
This will only affect users who dont have Justin's PR to not run steps that are run but still for customers who have do not have that code then it will still show RED and is still causing support cases to be generated for downstream.

Fixes #18307 - Remove red error on ES/gutterball

---

Rakefile

We need to make sure we're deleting not just foreman things, but puppet, apache, etc module caches too.  This explicitly whitelists only the modules katello-installer is shipping, it probably needs to be a bit more dynamic

fixes #18543 - explicitly delete non-katello modules from cache 

---

hooks/pre/15-check_java.rb

Checks for 1.7 or later, but text says greater than 1.7.

fixes #18537 - fix java check language to match actual check

---

hooks/boot/01-helpers.rb
hooks/boot/20-certs_update.rb
hooks/pre/20-certs_update.rb
hooks/pre/31-upgrade-puppet.rb

This PR adds an option called "--certs-reset" that will remove
any settings related to custom certs and then cause a new
self-signed CA to be created.

fixes #18322 - provide a way to reset certs to self-signed

---

hooks/pre/31-upgrade-puppet.rb

To test, spin up 3.3 box:
```
ansible-playbook pipelines/pipeline_katello_33.yml -e "forklift_state=up puppet_repositories_version=3"
```
SSH on to the box and run:
```
sudo rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
foreman-installer --disable-system-checks --upgrade-puppet
```
After you see it fail, copy patched file to `/usr/share/katello-intaller-base/hooks/pre` and re-run upgrade.

Fixes #18548 - Fix broken copy on Puppet 4 upgrade

---

.rubocop.yml
bin/foreman-proxy-certs-generate

Right now the org shown to users is Default_Organization regardless of it being that or what was set during the initial install.
Set my org at install to Katello Test:
[root@centos7 ~]# cat /etc/foreman-installer/scenarios.d/katello-answers.yaml | grep initial_organization
initial_organization: "Katello Test"
Run of certs generate:
[root@centos7 ~]# foreman-proxy-certs-generate --foreman-proxy-fqdn test.example.com --certs-tar /root/certs.tar
Installing             Done                                               [100%] [.................................................................................................................................]
Success!
To finish the installation, follow these steps:
If you do not have the smartproxy registered to the Katello instance, then please …

Fixes #18247 - Show initial org in proxy certs gen

---

hooks/boot/30-upgrade.rb
hooks/post/30-upgrade.rb

There exist several rake tasks in katello to resolve data integrity
issues (or mismatches) between it and the backend services
(pulp and candlepin).  This commit adds those steps to the installer
upgrade process so that the issues can be addressed automatically
versus the current behavior which may result in a failed upgrade
and then a need to run them manually.
Note: this is primarily for differences related to repository
and consumer resources.
The commit also includes an option  (--disable-resolve-mismatches)
to run the upgrade without making any changes.  It will still
run the tasks and report the changes that it would have made.

fixes #18405 - modify upgrade to include rake tasks to fix mismatches

---

hooks/post/10-post_install.rb

The hooks/post/10-post_install.rb file uses relative path with certs-tar option.
but I can not be used with. cause the certs-tar option requires absolute path.
The error was:
```
[root@katello01 ~]# foreman-proxy-certs-generate --foreman-proxy-fqdn "$FOREMAN_PROXY" --certs-tar "~/$FOREMAN_PROXY-certs.tar"
Parameter certs-tar invalid: ~/puppetca01.example.net-certs.tar is not one of regexes matching /^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/ or regexes matching /^\/([^\/\0]+(\/)?)+$/
Error during configuration, exiting
```

fixes #18797 - Not to use relative path with certs-tar option

---

bin/katello-certs-check

Added checks for the expiration date of the CA and the Certificate individually.
Had them checked separately as they can be created/developed separately in user environments.

Fixes #18849: katello-certs-check does not check expiration date

---

Rakefile
config/katello-answers.yaml
config/katello.migrations/170331152302-add-cli.rb
hooks/pre_migrations/01-migrate_legacy_foreman_installer_config.rb
hooks/pre_migrations/10-migrate_legacy_capsule_config.rb
hooks/pre_migrations/11-migrate_legacy_katello_config.rb

The recent change to hammer to verify SSL means we need to configure SSL and the hostname of the hammer config needs to match. The base configuration deploys at `https://localhost' and the `foreman::cli` manifest configure both the SSL certificate and sets the hostname properly. 
This would fix current bats failures -- http://ci.theforeman.org/view/Katello%20Pipeline/job/release_test_katello_nightly_el7/291/console

Fixes #19118 - Configure CLI on server

---

Puppetfile

The crane module is deprecated and now part of katello/pulp as pulp::crane.
I believe no migration is needed since it wasn't exposed directly to users.

Fixes #19180 - Remove crane

---

hooks/post/30-upgrade.rb

Deletes queue when :event queue was not created by system's hostname.

Fixes #20056 - deletes queue when its not created with hostname

---

hooks/pre/30-upgrade.rb

Call cpdb with full DB specification instead of relying on the defaults
This PR requires https://github.com/Katello/puppet-katello/pull/192

Refs #19667 - Support update of Candlepin with remote DB

---

Rakefile

At some point, a newer version of puppet in the 4.X line, puppet started installing puppet modules without the permissions they were uploaded to puppetforge. In our case, this can mean service-wait ends up not executable, and thus is not executed with the custom provider. The present outcome is that at times the proxy can start slow and registration will fail if this is not present. This is not a pretty solution but it solves the immediate breakages that can occur such as what is afflicting latest 3.4.1.2 installer package.

Fixes #20032 - Ensure service-wait is always executable

---

bin/katello-certs-check

Fixed a few grammer mistakes as well on some of the other functions.

Fixes #20307 - Add unicode char check to certs check

---

hooks/boot/01-helpers.rb
hooks/post/31-upgrade-puppet.rb
hooks/pre/31-upgrade-puppet.rb

The idea behind this change:
1) Only create the upgrade complete file when the post puppet upgrade step finishes
2) Add a check for puppet 4 installed, no --upgrade-puppet parameter passed, and create the puppet upgrade file
This last point is to try to prevent the case of installing with Pupept 4 and then being able to run --upgrade-puppet. Please check my logic adjustments carefully.

Fixes #20593 - Prevent puppet upgrade on fresh install

---

README.md

There were some missing `\` some extra `\` and most importantly,
using `"~"` in the path doesn't expand the `~`, which leads to
failues:
Parameter certs-tar invalid: ~/capsule.example.com-certs.tar is
not one of regexes matching /^(([a-zAError during configuration

Fixes in example snippets in README

---

hooks/boot/02-message-helpers.rb

before:
* Foreman Proxy is running at :#<Kafo::Param:20255140 @name="ssl_port" @default=8443 @value=9090 @type=integer (between 0 and 65535)>
after:
* Foreman Proxy is running at https://fp.example.com:8443

Refs #21060 - fix proxy success message to have the right url

---

hooks/boot/01-helpers.rb
hooks/post/31-upgrade-puppet.rb

When running rpm -q we only care about the result, not to log
the result of the execution. This could lead to ERROR output
when no real error is occurring.

Fixes #21222 - Don't log rpm -q output

---

hooks/pre/30-upgrade.rb

people sometimes place files at random places and then wonder why
things blow up, let's be nice to people

Fixes #21268 - only migrate qpid directories, not random files

---

bin/katello-certs-check

This is a reversion of 4cdf033184cf43cbb662b3ae5a0329dbe2baf442 except for the grammar changes.

Fixes #21345 - Allow unicode in certs

---

hooks/post/10-post_install.rb

During recent refactoring we've lost post-install handling of
successfull upgrade. Fixing the condition to get correct
message and "success file" back.

Fixes #21365 - Correct success message for upgrades

---

Gemfile

We use Ruby 2.0 style and 0.50 is the last to support that.

Pin rubocop to 0.50

---

checks/dns.rb

Adding to pre hooks after talks with @stbenjam because in support when setting up a customer reproducer we will need to use fake dns for an install to complete. Having it in the check will prevent us from using the --disable-system-checks override flag.

Fixes #15905 - Add forward/reverse dns check

---

hooks/post/30-upgrade.rb

Initial content import must be performed upon migrating to 3.6 due to [this change](https://github.com/Katello/katello/commit/946b2990c9a054babc9ad563e1b14c4161207b3e).
Since nightly build is broken, this can be tested on the centos7-katello-bats-ci box which has the above code. The changes here are easily applied manually.
There's an issue with pulp which causes the installer to fail at the clean_backend_objects step. Perform the workaround below before running the installer.
> yum install python-django
systemctl restart httpd pulp_workers pulp_resource_manager pulp_celerybeat pulp_streamer
The import_product_content step will likely run fast because you don't have any content to be imported. I don't think there's a need to test the rake task though, since it has been tested previously. …

Fixes #21936 - Import product content for 3.6

---

checks/dns.rb

When an IP address is included in the forward resolution, but has no
reverse record at all, we throw an exception instead of showing an
error message.
Before:
```
/usr/share/ruby/resolv.rb:130:in `getname': no name for 192.168.1.6
(Resolv::ResolvError) from /usr/share/ruby/resolv.rb:66:in `getname'
from ./dns.rb:27:in `block in <main>' from ./dns.rb:21:in `each'
from ./dns.rb:21:in `<main>'
```
After:
```
Forward DNS 192.168.1.6 did not reverse resolve to any hostname.
```

fixes #22173 - clear msg when fwd ip doesn't resolve

---

config/katello-answers.yaml
config/katello.migrations/180109093420-hammer-ssl-cert.rb

Reverts Katello/katello-installer#574, replaced with https://github.com/theforeman/puppet-foreman/pull/615

refs #22196 - do not configure hammer SSL CA certificate bundle

---

hooks/post/30-upgrade.rb

Relies on https://github.com/Katello/katello/pull/7142

fixes #22230 - reindex docker tags on upgrade

---

checks/dns.rb

Ruby < 2.3 doesn't support getname on IPv6 addresses: https://bugs.ruby-lang.org/issues/12112
My first thought was to just skip the test on old ruby:
```
next if ip.ipv6? && Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0')
```
@ekohl proposed using getresources, which works in my test environment that has real DNS servers. However, if a user expects /etc/hosts to work for forward/reverse lookups, it won't with getresources.  
Only Resolv::Hosts seems to do that, and that's broken with IPv6.
Thoughts?

refs #22173 - handle ipv6 on broken rubies

---

hooks/pre/21-check-hammer-credentials.rb

Cases I focused on are when the credentials are manually altered i.e. username is not the default 'admin' or the password is set. In such cases I presume the user has hammer configured and is using it so I'm preventing the installer to touch it.

Fixes #22431 - prevent migration of custom hammer credentials

---

hooks/post/30-upgrade.rb

`Host::Register` tasks have been removed as part of
https://github.com/Katello/katello/pull/7082.
This change adds a step to remove all tasks with label
`Actions::Katello::Host::Register`. Without this, already-executed tasks will
show as blank in the web UI.

Refs #21703 - remove registration tasks

---

hooks/boot/02-message-helpers.rb
hooks/post/10-post_install.rb

The devel scenario doesn't use the foreman module so this always fails.
Replaces https://github.com/Katello/katello-installer/pull/599

Refs #22558: Handle the devel credentials

---

bin/foreman-proxy-certs-generate

otherwise the following error is raised
$ foreman-proxy-certs-generate --help
/usr/sbin/foreman-proxy-certs-generate:88:in `ensure in <main>': undefined method `cleanup' for nil:NilClass (NoMethodError)
from /usr/sbin/foreman-proxy-certs-generate:88:in `<main>'
and that masks the real error that happened in initialize

Fixes #23345 - only call cleanup if we could initialize

---

hooks/boot/01-helpers.rb
hooks/pre/10-reset_feature.rb
hooks/pre_commit/05-puppet_certs_exist.rb

We usually don't have permissions to drop remote DBs. This fix lets installer to drop only tables and keep the empty DB during `--reset`. The original behavior (drop whole DB) is preserved for local databases.
https://github.com/Katello/katello-packaging/pull/499 is required for it to work

Refs #20550 - Reset remote database

---

hooks/pre/10-reset_feature.rb

To test, install a katello like this:
```
foreman-installer --scenario katello --katello-candlepin-db-name platypus --katello-pulp-db-name capybara
```
Run foreman-installer --reset with this PR, and notice it drops the correct databases.

fixes #23375 - use db names from puppet params

---

hooks/pre/30-upgrade.rb

43dd519593fbc85680934fbbaefe1566fe8b31e2 removed the --upgrade-puppet flag so this code should never be executed.

Refs #23470 - Remove mention of --upgrade-puppet flag

---

bin/katello-certs-check

I obtained a new server certificate for my Satellite server, but then found that yum couldn't fetch repository updates (errno 14, curl#60, NSS -8102, SEC_ERROR_INADEQUATE_KEY_USAGE). The certificate had X509v3 Key Usages of Digital Signature and Non Repudiation. When I got a new certificate which also included the Key Encipherment key usage, yum worked. (Red Hat Support case 02099325.)
This PR adds a check to katello-certs-check to ensure that the server certificate has the Key Encipherment key usage. With this patch, my old certificate fails katello-certs-check, and my new certificate passes.

Fixes #22598 - add check for key usage Key Encipherment

---

hooks/boot/10-reset_hook.rb

Hi,
This is one of a series of patches to address typos in `katello-installer --help` [#15963](http://projects.theforeman.org/issues/15963)
This diff addresses the `--reset` parameter's description, changing it from:
~~~
--reset                       This option will drop the Katello database and clear all subsequent backend data stores.You will lose all data! Unfortunately we
can't detect a failure at the moment so you should verify the success
manually. e.g. dropping can fail when DB is currently in use. (default: false)
~~~
To:
~~~
--reset                       This option will drop the Katello database and clear all subsequent backend data stores. You will lose all data!
Unfortunately, we can't detect a failure, so you should verify success manually.
Dropping can fail when the DB is …

Refs #15963 - katello-installer --help typos

---

hooks/pre/30-upgrade.rb

The installer should fix this. In the past it was needed because we started the http server inside the hook.

Fixes #23725 - Stop HTTP config mangling

---

hooks/post/30-upgrade.rb

this was missing from f4a983121401227119c55b229158c2075b07a9e9
I guess something  went wrong during a rebase.

refs #23292 - make s390x ks repos bootable

---

Puppetfile.lock

In puppet-mongodb 2.2.0 the mongodb_is_master fact was changed to ignore
a missing config file but introduced a regression when the fact was
used. In 2.2.1 this has been fixed.

Refs #23978 - Fix mongodb fact regression

---

.rubocop.yml
.rubocop_todo.yml
bin/foreman-proxy-certs-generate

Allow longer method length for MongoDB Engine Upgrade

Refs #24066 - Update Rubocop method length cop

---

hooks/init/31-upgrade-puppet.rb

Opened against katello-3.4 as master dropped this code already.

Fixes #24258 - Move autosign entries when upgrading puppet

---

config/foreman-proxy-content-answers.yaml
config/foreman-proxy-content.migrations/180813131441-unmanage-puppet-group.rb
config/katello-answers.yaml
config/katello.migrations/180813131441-unmanage-puppet-group.rb

This is a workaround when using the Puppet certificates but not managing Puppet. In the Katello context we never do that and it can result in a duplicate file declaration.

Fixes #18806 - Never manage the Puppet group

---

hooks/pre/20-certs_update.rb

Now katello-certs-check command does not accept -r ( request file) so this option should be removed from the 20-certs_update.rb hook.

Fixes #24632 - cert-req needs to be removed

---

hooks/pre/30-upgrade.rb

There is no PostgreSQL required on the Proxy.

Fixes #25011 - only start PostgreSQL in the Katello scenario

---

config/foreman-proxy-content.migrations/160120212700-foreman-proxy.rb
config/foreman-proxy-content.migrations/160919172842_infoblox.rb
config/foreman-proxy-content.migrations/161004173201_smart_proxy_ansible.rb
config/katello.migrations/160120212701-foreman-proxy.rb
config/katello.migrations/160919172842_infoblox.rb
config/katello.migrations/161004173201_foreman_ansible.rb

Kafo hasn't needed these trivial mappings and we eventually clear them
anyway.

Fixes #25056 - Remove mappings

---

hooks/pre/10-reset_feature.rb

In EL6 the service was named tomcat6. The hook autodetects this but since we only support EL7 we can hardcode it. We can also move to systemctl instead of service.

Fixes #25061 - Remove EL6 compat in reset_candlepin

---

config/foreman-proxy-content.migrations/180829115142_change_rex_ssh_dir.rb
config/katello.migrations/180829115142_change_rex_ssh_dir.rb

The directory changed in packaging. This reflects that change in the
answer files.
(cherry picked from commit 8db3201bc3e8e1bf7dea517cc92bfc480d0994cd)

[CP] Missed 3.7.1 pick

---

config/foreman-proxy-content.migrations/181012141418-qdrouterd-listen-ipv6.rb
config/katello.migrations/181012141418-qdrouterd-listen-ipv6.rb

The defaults in puppet-foreman_proxy_content changed and this reflects that change for existing users.

Refs #12386 - Let qdrouterd listen on IPv6

---

bin/katello-certs-check

Results of testing:
~~~
Katello cert:
[root@satellite1 ~]# ./katello-certs-check -b /root/ca.pem -k /root/server.key -c /root/server.crt 
Checking server certificate encoding: 
[OK]
Checking expiration of certificate: 
[OK]
Checking expiration of CA bundle: 
[OK]
Checking if server certificate has CA:TRUE flag 
[OK]
Checking to see if the private key matches the certificate: 
[OK]
Checking CA bundle against the certificate file: 
[OK]
Checking Subject Alt Name on certificate 
[OK]
Checking Key Usage extension on certificate for Key Encipherment 
[OK]
Validation succeeded
To install the Katello main server with the custom certificates, run:
foreman-installer --scenario katello \
--certs-server-cert "/root/server.crt" \
--certs-server-key "/root/server.key" \
--certs-server-ca-cert …

Fixes #25306 - Add space after command output in kcc

---

hooks/pre/10-reset_feature.rb

Removed the SCL command from the remote reset because we install `mongo-syspaths` now so `mongo` works correctly.

Fixes #23620 - Fix reset for local & remote MongoDB.

---

hooks/post/30-upgrade.rb

In kafo 2.1.0 the module_enabled? hook function doesn't handle the case where a module isn't present at all. The Kafo::Helpers version of it does.
(cherry picked from commit 7211b9321cc340fd61e76ee862004e42e7666ef6)
See https://github.com/Katello/katello-installer/pull/712 as well

Fixes #25386 - Use the module_enabled? helper

---

bin/foreman-proxy-certs-generate
config/foreman-proxy-content.yaml
config/katello.yaml

Since kafo 1.0.7 this option isn't read anymore so it can be removed from the configs.

Fixes #25563 - Remove default_values_dir from configs

---

hooks/pre/30-upgrade.rb

This removes a dependency cycle caused by prior installations.
Reflects https://github.com/theforeman/puppet-katello/commit/4a0f1b22077d44d2cd2e5c068fa7d9750c0ee602

Drop Foreman from Apache group on upgrade

---

bin/katello-certs-check

The use of == is a bash-only feature. Since we're using this already, we might as well go all the way and use the safer [[ ]] checks.
Using $() instead of `` is also a better practice because it allows nesting and slightly easier to read.

Fixes #25665 - Use the bash comparisons can function calls
