Katello/katello-installer

hooks/pre/30-upgrade.rb

fixes #10219 - use su instead of sudo

---

hooks/post/30-upgrade.rb

(cherry picked from commit bc091d97eef4b1151c9bbc89e0b6f75414004d01)

fixes #10512 - add 2.2 upgrade rake tasks to upgrade hook

---

bin/capsule-remove
katello-installer.spec

Added capsule remove script and modified .spec file

Fixes #10538 - Adding capsule-remove script

---

katello-installer.spec

See https://tickets.puppetlabs.com/browse/PUP-341

Fixes #10648 - the --profile parameter was introduced in puppet 3.4.0

---

.gitignore
README.md

Forgot the most important thing!

Add Travis Icon

---

Puppetfile
README.md

Also sorts ours alphabetically

fixes #11356 - clean up puppetfile and add new reqs

---

Puppetfile
hooks/post/30-upgrade.rb
hooks/pre/10-reset_feature.rb

Goes with https://github.com/Katello/katello-packaging/pull/82 and https://github.com/Katello/puppet-katello/pull/85

Fixes #10291 - removes elasticsearch

---

hooks/pre/30-upgrade.rb

See http://projects.theforeman.org/issues/13520

Fixes #13520 - Use correct mongod.conf path in 30-upgrade hook for EL7

---

hooks/post/30-upgrade.rb

this goes along with Katello/katello#5744

refs #13454 - add docker v1 repository removal into upgrade actions

---

hooks/post/10-post_install.rb

removes url that is not for a customer to visit

Fixes #13250 - Remove capsule 9090 url

---

hooks/init/10-puppet-profile-on-el6.rb

Re-add puppet settings lost during scenarification

Refs #7064 - run puppet with --profile on Ruby 1.8.7

---

hooks/post/10-post_install.rb

Removed steps to register capsule since it would be registered already.

Fixes #14098 - Removed steps to register

---

Puppetfile
config/answers.sam-installer.yaml
config/katello-answers.yaml
config/katello-devel-answers.yaml
config/katello-devel.migrations/160503102719-gutterball.rb
config/katello-devel.yaml
config/katello.migrations/160503102427-gutterball.rb
config/katello.yaml
config/sam-installer.migrations/160503103137-gutterball.rb
config/sam-installer.yaml
hooks/post/30-upgrade.rb
hooks/pre/30-upgrade.rb

Main PR: https://github.com/Katello/katello-packaging/pull/213

Refs #14858 - removes gutterball

---

hooks/post/10-post_install.rb

Revert "Fixes #15325 - Handle nil params"
This reverts commit 0aa563937629ca8ab66c76e4705b8c917b927550.

Fixes #15327 - Handle nil params

---

bin/capsule-remove

Fixes #15381 - Added help to capsule-remove

---

bin/capsule-remove

adding option to do --unattended for capsule remove.

Fixes #16003 - Adding unattended to capsule remove

---

Gemfile
Rakefile
config/capsule.migrations/160824145544-parser_cache.rb
config/capsule.yaml
config/katello-devel.migrations/160824145544-parser_cache.rb
config/katello-devel.yaml
config/katello.migrations/160824145544-parser_cache.rb
config/katello.yaml

depends on theforeman/kafo#166.

fixes #15938 - generate parser cache for kafo

---

README.md

Very small change in Readme file.

fixed - corrected the name of option in README.md

---

Gemfile

This won't build with less than 1.0.1

bump kafo to 1.0.1

---

config/katello-answers.yaml
config/katello.migrations/161002132418-keepalive.rb

https://github.com/Katello/puppet-katello/pull/141

Fixes #17094: Move keepalive settings from katello to foreman

---

config/capsule.migrations/161004173201_smart_proxy_ansible.rb
config/katello.migrations/161004173201_foreman_ansible.rb

This reverts commit 65b239ac9ef497a4acf048d42df6f8cc75be9818.

Revert "Fixes #16789 - add ansible installer migrations (#406)"

---

hooks/post/11-create_sslconf.rb

Workaround until mod_ssl packaging is corrected.

Fixes #16972 - Adding post hook to create ssl.conf file

---

Gemfile
config/katello-answers.yaml
config/katello.migrations/161130090556-server_ssl_crl_blank.rb

Needs https://github.com/theforeman/puppet-foreman/pull/509

fixes #17534 - server_ssl_crl should be blank string not boolean

---

config/capsule.migrations/160919172842_infoblox.rb
config/katello.migrations/160919172842_infoblox.rb

This reverts commit 9ebd0734cf641ed22d88b6884526e82c09bf5885.

Revert "Fixes #16788 - Add migration for infoblox plugins (#405)"

---

hooks/post/11-create_sslconf.rb
hooks/post/29-create_package_httpd_conf.rb
hooks/pre/29-remove_package_httpd_conf.rb
hooks/pre/29-remove_sslconf.rb
hooks/pre/30-upgrade.rb

(cherry picked from commit ad98cc5f97b74f27853f548fd655db7de77c7f9f)

additional cherry pick for 3.2

---

hooks/post/29-create_package_httpd_conf.rb
hooks/pre/30-upgrade.rb

This fixes some issues that users found when upgrading to 3.2.2

3.2.2 cherry-picks

---

Gemfile

as its needed for rake pkg:generate_source

Add puppet-strings dependency

---

bin/katello-certs-check

Updated steps for updating certs tar for an already existing foreman-proxy

Fixes #18310 - Update certs-check for proxy

---

hooks/pre/31-upgrade-puppet.rb

puppet-agent-oauth needs to be installed before stopping services

fixes #18068 - ensure pulp is available during puppet upgrade

---

hooks/pre/31-upgrade-puppet.rb

(cherry picked from commit d8c68d12c7e4c7f2e6996bb53800a879d7e8141b)

Fixes #18890: Change Katello::Helpers to Kafo::Helpers

---

Rakefile

(cherry picked from commit f50d51a9a514ba6292be5770f6c77e682de82c27)

Fixes #23002 - Ensure service-wait is always executable

---

hooks/pre/30-upgrade.rb

Refs #20239 - update backup path in script

---

hooks/pre/30-upgrade.rb

Tested on 3.4 - > 3.5 and 6.2 -> 6.3 and looks good.

Fixes #21708 - remove services starting on upgrade

---

hooks/post/30-upgrade.rb

See: https://github.com/Katello/katello/pull/7175

refs #22446 - republish file repos on 3.6 upgrade

---

Puppetfile
Rakefile

(cherry picked from commit 3c171512e72d8dbe3c1431b517df11cc69e94cfb)

Fixes #23368 - Drop service_wait module

---

hooks/boot/31-upgrade-puppet.rb

c93247548e1cf096cab43af889810cd880814480 omitted this.

Fixes #23603 - Correct --upgrade-puppet help text

---

hooks/pre/21-check-hammer-credentials.rb

(cherry picked from commit c4504414efb8ae9aa1032bd80072a656f8c26b55)

Cherry picks for 3.6.1

---

hooks/post/30-upgrade.rb

(cherry picked from commit f4a983121401227119c55b229158c2075b07a9e9)

Fixes #23292 - make s390x ks repos bootable

---

config/foreman-proxy-content.migrations/180702133937-set-puppet-integration-answer.rb
config/katello.migrations/180702133937-set-puppet-integration-answer.rb

This answer is still needed to determine whether the certs for puppet integration need to be placed.

Fixes #24088 - Maintain the puppet answer in foreman_proxy_content

---

Puppetfile
Puppetfile.lock
hooks/post/30-upgrade.rb

(cherry picked from commit b70dde1807e6b96c92d5f893d67e1172fd8a9722)

[CP] 3.7 Cherry picks

---

Rakefile

* No longer users global variables
* Aligns mod options to the longest module name
* Ignores modules on a specific git reference

Improve pinning modules

---

hooks/pre_validations/31-upgrade-puppet.rb

(cherry picked from commit 08d694639c2b8a752fa6c8166dea10d5a6fed2c9)

Fixes #24752 - reset server_puppetserver_metrics

---

config/foreman-proxy-content.migrations/180829115142_change_rex_ssh_dir.rb
config/katello.migrations/180829115142_change_rex_ssh_dir.rb

The directory changed in packaging. This reflects that change in the
answer files.

Refs #24628 - Add migrations for the REX SSH dir

---

hooks/post/30-upgrade.rb

No need to remove MongoDB log files

---

hooks/post/30-upgrade.rb

Not making this (3.8.1) against master because of https://github.com/Katello/katello-installer/pull/657 (3.9)

Refs #24730: add upgrade step clear_checksum_type

---

checks/lang.rb

We require a UTF-8 locale and C doesn't allow to output that.

Fixes #25516 - Check LC_ALL is not set to C

---

hooks/pre/31-mongo_storage_engine.rb

Was not restoring the DB due to the directory not being defined and the sed command was not removing the old message. Added drop to the restore command becuase I noticed it was having some dupe collection messages. Tested on a 6.5 snap
`don't know what to do with subdirectory "mongodb_engine_upgrade/pulp_database", skipping...`
```
Before engine upgrade:
[root@mongo ~]# du -sh /var/lib/mongodb/
2.9G	/var/lib/mongodb/
[root@mongo ~]# ll /var/lib/mongodb/
total 2129948
drwxr-xr-x. 2 mongodb mongodb        155 Dec  5 14:30 diagnostic.data
drwxr-xr-x. 2 mongodb mongodb         29 Dec  5 14:11 journal
-rw-------. 1 mongodb mongodb   67108864 Dec  5 14:10 local.0
-rw-------. 1 mongodb mongodb   16777216 Dec  5 14:10 local.ns
-rwxr-xr-x. 1 mongodb mongodb          6 Dec  5 14:10 mongod.lock …
```

Fixes #25634 - update db location and sed on removal
